Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -48,6 +48,10 @@ jobs:
 
       - name: Pre-destroy Cleanup (CRDs)
         run: |
+          if [ -z "${{ vars.CLUSTER_NAME }}" ]; then
+            echo "Error: CLUSTER_NAME variable is NOT set in GitHub Variables."
+            exit 1
+          fi
           aws eks update-kubeconfig --name ${{ vars.CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}
           echo "Deleting all CustomResourceDefinitions to prevent orphan resources..."
           kubectl delete crd --all --ignore-not-found=true
